apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/istio-istiod
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
