#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: vm
    username: ubuntu
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    # ubuntu
  ssh:
    install-server: true
    allow-pw: false
  packages:
    - openssh-server
  timezone: "Etc/UTC"
  updates: all
  shutdown: poweroff
  late-commands:
    # add ip address to TTY login screen
    - echo 'IyEvdXNyL2Jpbi9lbnYgYmFzaApzZXQgLWV1eAoKIyBodHRwczovL3NlcnZlcmZhdWx0LmNvbS9xdWVzdGlvbnMvMjA5NTk5L2hvdy10by1zZXR1cC1ldGMtaXNzdWVzLXRvLXNob3ctdGhlLWlwLWFkZHJlc3MtZm9yLWV0aDAKCiMgZG9uJ3QgcnVuIGluIG1hY09TCmlmIFtbICEgLWUgL1VzZXJzIF1dICYmIHdob2FtaSB8IGdyZXAgInJvb3QiIDsgdGhlbgogIGlmIFtbICEgLWYgL2V0Yy8uaXNzdWUub3JpZyBdXSA7IHRoZW4KICAgIGNwIC9ldGMvaXNzdWUgL2V0Yy8uaXNzdWUub3JpZwogIGZpCiAgaW50PSQoIGxzIC9zeXMvY2xhc3MvbmV0IHwgZ3JlcCAiZW5wIiB8IGhlYWQgLTEgKQogIHNlZCAtciAicy9eVWJ1bnR1L1xcXDRceyRpbnRcfSAtIFVidW50dS8iIDwgL2V0Yy8uaXNzdWUub3JpZyA+IC9ldGMvaXNzdWUKICBzeXN0ZW1jdGwgcmVzdGFydCBnZXR0eUB0dHkxCmZpCg==' | base64 -d > /target/sbin/ubuntu-tty-update.sh
    - curtin in-target -- chmod 755 /sbin/ubuntu-tty-update.sh
    - curtin in-target -- test -d /etc/network/if-up.d || curtin in-target install -d -m 755 -o root -g root /etc/network/if-up.d
    - curtin in-target -- ln -sf /sbin/ubuntu-tty-update.sh /etc/network/if-up.d/update-issue
    - curtin in-target -- test -d /etc/network/if-post-down.d || curtin in-target install -d -m 755 -o root -g root /etc/network/if-post-down.d
    - curtin in-target -- ln -sf /sbin/ubuntu-tty-update.sh /etc/network/if-post-down.d/update-issue
    # extend logical volume
    - curtin in-target -- lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv
    - curtin in-target -- resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv
  user-data:
    users:
      - name: lab
        homedir: /home/lab
        shell: /bin/bash
        lock_passwd: true
        gecos: lab
        groups: adm, cdrom, dip, lxd, plugdev, sudo
        primary_group: lab
        ssh_import_id:
          - gh:johnko
        sudo: ALL=(ALL) NOPASSWD:ALL
      - name: ubuntu
        expiredate: "2000-01-01"
        homedir: /home/ubuntu
        shell: /bin/bash
        lock_passwd: true
        gecos: ubuntu
        groups: ubuntu
        primary_group: ubuntu
        sudo: false
    package_update: true
    package_upgrade: true
    packages:
      - openssh-server
      - docker.io
      - docker-compose
    ssh_pwauth: false
