#cloud-config
autoinstall:
  version: 1
  ssh:
    install-server: true
    allow-pw: false
  packages:
    - openssh-server
  timezone: "Etc/UTC"
  updates: all
  shutdown: poweroff
  user-data:
    users:
      - name: lab
        homedir: /home/lab
        shell: /bin/bash
        lock_passwd: true
        gecos: lab
        groups: adm, cdrom, dip, lxd, plugdev, sudo
        primary_group: lab
        ssh_import_id:
          - gh:johnko
        sudo: ALL=(ALL) NOPASSWD:ALL
    package_update: true
    package_upgrade: true
    packages:
      - openssh-server
      - docker.io
      - docker-compose
    ssh_pwauth: false
