#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

OMIT=""
for iface in flannel.1 cni0 docker0 lo ; do
  if ip addr show  >/dev/null 2>&1 ; then
    OMIT="$OMIT"$(ip addr show $iface | grep 'inet ' | awk '{ print $2 }' | tr "\n" '|')
  fi
done
OMIT="$OMIT"255.255.255.255
ip addr | grep 'inet ' | awk '{ print $2 }' | grep -v -E "$OMIT"
