#!/bin/sh
# https://askubuntu.com/questions/217358/how-can-i-display-my-machines-ip-address-on-a-tty-login-screen
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

MSG=$(cat /etc/issue | grep -v ipv4)
IP=$(ip addr | grep 'inet ' | grep -v '127' | awk '{ print $2 }' | tr "\n" '_' | sed 's,_,   ,g')
printf "%s\n\n%s\n\n" "$MSG" "ipv4: $IP" > /etc/issue
