apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/knative
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false # because the ClusterRole flipflops
