apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    istio:
      local-gateway.knative-serving.knative-local-gateway: "knative-local-gateway.istio-system.svc.cluster.local"
  # omitted below to be able to use istio
  #   network:
  #     ingress-class: kourier.ingress.networking.knative.dev
  # ingress:
  #   kourier:
  #     enabled: true
