apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-microk8s
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/ingress-nginx
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        controller:
          kind: DaemonSet
          metrics:
            enabled: true
        serviceAccount:
          name: nginx-ingress-microk8s-serviceaccount
        fullnameOverride: nginx-ingress-microk8s
  syncPolicy: {}
