apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/traefik
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        deployment:
          kind: DaemonSet
        logs:
          general:
            level: DEBUG
        podSecurityContext: # danger but needed if listening on port 53
          runAsNonRoot: false
          runAsUser: 0
        ports:
          dnstcp:
            expose: true
            exposedPort: 53
            port: 53
            protocol: TCP
          dnsudp:
            expose: true
            exposedPort: 53
            port: 53
            protocol: UDP
        securityContext: # danger but needed if listening on port 53
          capabilities:
            add:
            - NET_BIND_SERVICE
        service:
          externalIPs:
          - 192.168.2.9  # LABCLUSTER_IP
          type: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
