apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/metrics-server
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        args:
          - --secure-port=10250
          - --kubelet-certificate-authority=/ca/ca.crt
        extraVolumeMounts:
          - mountPath: /ca
            name: ca-dir
        extraVolumes:
          - name: ca-dir
            configMap:
              name: kube-root-ca.crt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
