apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/traefik
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        deployment:
          kind: DaemonSet
        service:
          type: ClusterIP
          externalIPs:
            - 192.168.2.9  # LABCLUSTER_IP
        ports:
          dnstcp:
            port: 53
            expose: true
            exposedPort: 53
            protocol: TCP
          dnsudp:
            port: 53
            expose: true
            exposedPort: 53
            protocol: UDP
        securityContext: # danger but needed if listening on port 53
          capabilities:
            add:
              - NET_BIND_SERVICE
        podSecurityContext: # danger but needed if listening on port 53
          runAsNonRoot: false
          runAsUser: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
