apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/metrics-server
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        defaultArgs:
          - --cert-dir=/tmp
          - --kubelet-preferred-address-types=ExternalIP,InternalIP,Hostname
          - --kubelet-use-node-status-port
          - --metric-resolution=15s
        args:
          - --secure-port=10250
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
