apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/namespaces
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        namespaces:
        - argocd
        - cert-manager
        - istio-system
        - knative-serving
        - openfaas
        - openfaas-fn
        - pihole
        - rook-ceph
        - traefik
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
