apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/coredns
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 2
        service:
          name: kube-dns
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - coredns
              topologyKey: "kubernetes.io/hostname"
        k8sAppLabelOverride: kube-dns
        deployment:
          name: coredns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
