apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/argo-cd
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        redis-ha:
          enabled: true
          replicas: 1
          hardAntiAffinity: false
          haproxy:
            replicas: 1
        controller:
          replicas: 1
        server:
          replicas: 1
        repoServer:
          replicas: 1
        applicationSet:
          replicaCount: 1
  syncPolicy: {}
