apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/coredns
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - coredns
              topologyKey: kubernetes.io/hostname
        fullnameOverride: coredns
        k8sAppLabelOverride: kube-dns
        podDisruptionBudget:
          minAvailable: 1
        priorityClassName: system-cluster-critical
        replicaCount: 1
        rollingUpdate:
          maxUnavailable: 0
        servers:
        - plugins:
          - name: errors
          - configBlock: |-
              lameduck 5s
            name: health
          - name: ready
          - configBlock: |-
              class error
            name: log
            parameters: .
          - configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
            name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
          - configBlock: |-
              ttl 60
              reload 15s
              fallthrough
            name: hosts
            parameters: /etc/coredns/NodeHosts
          - name: prometheus
            parameters: :9153
          - name: forward
            parameters: . 1.1.1.1 8.8.8.8
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
          port: 53
          zones:
          - zone: .
        service:
          name: kube-dns
        serviceAccount:
          create: true
          name: coredns
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
  syncPolicy: {} # disable autosync to avoid port name flipflops
