apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/coredns
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: k8s-app
                      operator: In
                      values:
                        - coredns
                topologyKey: "kubernetes.io/hostname"
        fullnameOverride: coredns
        k8sAppLabelOverride: kube-dns
        podDisruptionBudget:
          minAvailable: 1
        priorityClassName: system-cluster-critical
        replicaCount: 2
        rollingUpdate:
          maxUnavailable: 0
        servers:
          - zones:
              - zone: .
            port: 53
            plugins:
              - name: errors
              - name: health
                configBlock: |-
                  lameduck 5s
              - name: ready
              - name: log
                parameters: .
                configBlock: |-
                  class error
              - name: kubernetes
                parameters: cluster.local in-addr.arpa ip6.arpa
                configBlock: |-
                  pods insecure
                  fallthrough in-addr.arpa ip6.arpa
              - name: hosts
                parameters: /etc/coredns/NodeHosts
                configBlock: |-
                  ttl 60
                  reload 15s
                  fallthrough
              - name: prometheus
                parameters: :9153
              - name: forward
                parameters: . 8.8.8.8 8.8.4.4
              - name: cache
                parameters: 30
              - name: loop
              - name: reload
              - name: loadbalance
        service:
          name: kube-dns
        serviceAccount:
          create: true
          name: coredns
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
  syncPolicy: {}
