apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/metrics-server
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
    helm:
      values: |
        args:
        - --kubelet-insecure-tls
        containerPort: 4443
        nodeSelector:
          kubernetes.io/arch: amd64
          kubernetes.io/os: linux
        updateStrategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 0
          type: RollingUpdate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
