annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Fix wrong namespaceSelector in ServiceMonitor when using custom monitoring namespace
apiVersion: v2
appVersion: 1.10.1
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS
  Services
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
keywords:
- coredns
- dns
- kubedns
maintainers:
- name: mrueg
- name: haad
- name: HagaiBarel
name: coredns
sources:
- https://github.com/coredns/coredns
type: application
version: 1.24.4
