version: "3.8"

# reference: https://k3d.io/v5.5.1/usage/multiserver/
# https://docs.k3s.io/datastore/ha-embedded

services:
  k3s:
    container_name: k3s
    image: rancher/k3s:v1.26.4-k3s1
    command: >
      server --tls-san=labcluster
    environment:
      - K3S_TOKEN=lab.local
      - K3S_DATASTORE_ENDPOINT=postgres://database:5432/kubernetes
      - K3S_DATASTORE_CAFILE=/var/lib/rancher/k3s/ca.crt
    extra_hosts:
      - "database:192.168.2.232"
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - k3sserver:/var/lib/rancher/k3s/server
      - k3snode:/etc/rancher/node
      - ./pgsql-server.pem:/var/lib/rancher/k3s/ca.crt:ro

volumes:
  k3sserver:
  k3snode:
