Vagrant.configure("2") do |config|
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  # Keys_only false so that beaker vagrant can login
  config.ssh.keys_only = false

  # config.ssh.insert_key = true

  # Path to your privatekey
  config.ssh.private_key_path = ["~/.ssh/id_rsa"]

  # Provision script to setup the authorized_keys with your publickey
  config.vm.provision "insecure_private_key", type: "shell", inline: <<-SHELL
    mkdir -p /home/vagrant/.ssh
    [ -e /home/vagrant/.ssh/authorized_keys ] && mv /home/vagrant/.ssh/authorized_keys /home/vagrant/.ssh/authorized_keys2

    # Replace with your publickey
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" > /home/vagrant/.ssh/authorized_keys

    chown vagrant: /home/vagrant/.ssh
    chmod 700      /home/vagrant/.ssh
    chown vagrant: /home/vagrant/.ssh/authorized_keys
    chmod 644      /home/vagrant/.ssh/authorized_keys
  SHELL
end
