annotations:
  artifacthub.io/changes: "- \"feat: support API basePath\"\n- \"feat: make dashboard
    toggleable\"\n- \"feat: :package: support Traefik Hub v3.18 pluginRegistry feature\"\n-
    \"feat(traefik-hub): add mcpgateway option\"\n- \"feat(observability): :mag: add
    per entrypoint observability\"\n- \"feat(metrics): :chart_with_upwards_trend:
    add OTLP resourceAttributes support\"\n- \"feat(logs): :memo: add missing support
    of OTLP logs\"\n- \"chore(release): \U0001F680 publish traefik 37.2.0\"\n- \"chore(hub):
    :twisted_rightwards_arrows: update hub and proxy mapping for v3.18\"\n"
apiVersion: v2
appVersion: v3.5.3
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.22.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 37.2.0
