apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/charts/istio/gateway
    repoURL: https://github.com/johnko/homedir.git
    targetRevision: HEAD
  syncPolicy: {}
