version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:14.2@sha256:2c954f8c5d03da58f8b82645b783b56c1135df17e650b186b296fa1bb71f9cfd
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: host
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./pgsql-server.pem:/var/lib/postgresql/server.crt:ro
      - ./pgsql-server.key:/var/lib/postgresql/server.key:ro

volumes:
  postgres:
