#cloud-config
users:
  - name: lab
    plain_text_passwd: 'lab'
    home: /home/lab
    shell: /bin/bash
    lock_passwd: True
    gecos: lab
    groups: [adm, cdrom, dip, lxd, plugdev, sudo]
    primary_group: lab
    ssh_import_id:
      - gh:johnko

package_update: true
package_upgrade: true
packages:
  - openssh-server
