apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pihole-dnstcp
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  entryPoints:
    - dnstcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: pihole-dns-tcp
          port: 53
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: pihole-dnsudp
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  entryPoints:
    - dnsudp
  routes:
    - services:
        - name: pihole-dns-tcp
          port: 53
