## See more docs at https://hub.docker.com/r/atlassian/confluence-server/
version: "3.5"

services:
    confluence:
        container_name: confluence-7.11.2
        image: atlassian/confluence-server:7.11.2
        ports:
            - 127.0.0.1:8090:8090
            - 127.0.0.1:8091:8091
        restart: unless-stopped
        volumes:
            - data:/var/atlassian/application-data/confluence

volumes:
    data:
