{{- range $app, $val := .Values.cluster.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argocd
  {{- if .annotations }}
  annotations: {{ .annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  destination:
    namespace: {{ .destination.namespace }}
    server: https://kubernetes.default.svc
  project: {{ .project | default "default" }}
  source:
    path: {{ .source.path }}
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision | default "HEAD" }}
    helm:
    {{- if .source.helm.values }}
      values: |{{ .source.helm.values | toYaml | nindent 8 }}
    {{- else }}
      values: {}
    {{- end }}
  {{- if .syncPolicy }}
  syncPolicy: {{ .syncPolicy | toYaml | nindent 4 }}
  {{- else }}
  syncPolicy: {}
  {{- end }}
{{- end }}
