apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pihole-dnstcp
  namespace: {{ .Values.cluster.apps.pihole.destination.namespace }}
  {{- if .Values.cluster.apps.pihole.annotations }}
  annotations: {{ .Values.cluster.apps.pihole.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - dnstcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: pihole-dns-tcp
          port: 53
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: pihole-dnsudp
  namespace: {{ .Values.cluster.apps.pihole.destination.namespace }}
  {{- if .Values.cluster.apps.pihole.annotations }}
  annotations: {{ .Values.cluster.apps.pihole.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - dnsudp
  routes:
    - services:
        - name: pihole-dns-tcp
          port: 53
