all:
  children:
    sticks:
      hosts:
        # add in ~/.ssh/config
        stick1:
        stick2:
    ubuntu:
      children:
        sticks:
      vars:
        # set up ssh user name and path to python3
        ansible_become_method: sudo
        # https://medium.com/opsops/how-to-pass-password-to-ansible-from-environment-variable-bd5c566bc8a1
        ansible_become_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
        ansible_python_interpreter: '/usr/bin/env python3'
        ansible_user: lab
