all:
  # add hosts in ~/.ssh/config
  children:
    database:
      hosts:
        stick2:
          vars:
            ucarp_options: --preempt --advskew=100
    sticks:
      hosts:
        stick1:
          vars:
            ucarp_options: --advskew=200
      children:
        database:
    ubuntu:
      children:
        sticks:
  vars:
    # set up ssh user name and path to python3
    ansible_become_method: sudo
    ansible_python_interpreter: '/usr/bin/env python3'
    ansible_user: lab
    # https://medium.com/opsops/how-to-pass-password-to-ansible-from-environment-variable-bd5c566bc8a1
    ansible_become_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    labcluster_ip: '{{ lookup("env", "LABCLUSTER_IP") }}'
