all:
  # add hosts in ~/.ssh/config
  children:
    database:
      hosts:
        vm1:
          vars:
            ucarp_options: --advskew=100 --advbase=5 --preempt
            ucarp_service_enabled: true
    k3sprimary:
      children:
        database:
    k3sservers:
      children:
        sticks:
        vms:
    mac:
      hosts:
        r2d2:
      vars:
        ansible_become_password: '{{ lookup("env", "ANSIBLE_PASSWORD_MAC") }}'
    sticks:
      hosts:
        stick2:
          vars:
            ucarp_options: --advskew=500 --advbase=5
            ucarp_service_enabled: true
    ubuntu:
      children:
        sticks:
        vms:
    ucarpservers:
      children:
        sticks:
        vms:
    vms:
      children:
        database:
  vars:
    # set up ssh user name and path to python3
    ansible_become_method: sudo
    ansible_python_interpreter: '/usr/bin/env python3'
    ansible_user: lab
    # https://medium.com/opsops/how-to-pass-password-to-ansible-from-environment-variable-bd5c566bc8a1
    ansible_become_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    labcluster_ip: '{{ lookup("env", "LABCLUSTER_IP") }}'
