- hosts: database
  become: true
  become_user: root
  tasks:
    - name: Copy app scripts
      copy:
        src: './{{ item.app }}/'
        dest: '{{ ansible_user_dir }}/{{ item.app }}/'
        force: true
        directory_mode: '700'
        mode: '644'
      loop:
        - { app: postgres }
    - name: Run app
      shell:
        chdir: '{{ ansible_user_dir }}/{{ item.app }}'
        cmd: 'bash run-{{ item.app }}.sh up'
      loop:
        - { app: postgres }
    - name: Fetch cert
      fetch:
        src: /etc/ssl/pgsql-server.pem
        dest: ./tmp/pgsql-server.pem
        flat: true

- hosts: k3sservers
  become: true
  become_user: root
  tasks:
    - name: Copy cert
      copy:
        src: ./tmp/pgsql-server.pem
        dest: /etc/ssl/pgsql-server.pem
        force: true
        mode: '644'
    - name: Copy app scripts
      copy:
        src: './{{ item.app }}/'
        dest: '{{ ansible_user_dir }}/{{ item.app }}/'
        force: true
        directory_mode: '700'
        mode: '644'
      loop:
        - { app: k3s-server }
    - name: Template k3s files
      template:
        src: './{{ item.app }}/{{ item.file }}.j2'
        dest: '{{ ansible_user_dir }}/{{ item.app }}/{{ item.file }}'
        force: true
        mode: '{{ item.mode }}'
      loop:
        - { app: k3s-server, file: docker-compose.yml, mode: '644' }
    - name: Run app
      shell:
        chdir: '{{ ansible_user_dir }}/{{ item.app }}'
        cmd: 'bash run-{{ item.app }}.sh up'
      loop:
        - { app: k3s-server }

    - name: Extract kubeconfig
      shell: docker cp k3s:/etc/rancher/k3s/k3s.yaml /var/tmp/k3s.yaml
      when:
        - lookup('ansible.builtin.fileglob', './tmp/k3s.yaml') == []
        - inventory_hostname not in groups['k3sprimary']
        - ansible_facts['distribution'] in ['Ubuntu']
    - name: Fetch kubeconfig
      fetch:
        src: /var/tmp/k3s.yaml
        dest: ./tmp/k3s.yaml
        flat: true
      when:
        - lookup('ansible.builtin.fileglob', './tmp/k3s.yaml') == []
        - inventory_hostname not in groups['k3sprimary']
        - ansible_facts['distribution'] in ['Ubuntu']
