- hosts: ubuntu
  become: true
  become_user: root
  tasks:
    - name: Set fact for uptime_days
      # https://iam-j.github.io/iac/ansible-machine-uptime/
      # https://stackoverflow.com/questions/74318579/how-to-calculate-ansible-uptime-seconds-and-output-this-in-os-csv
      set_fact:
        uptime_days: "{{ (ansible_facts['uptime_seconds'] | int / 86400) | round(1) }}"
    - name: Set fact for uptime_hours
      set_fact:
        uptime_hours: "{{ (ansible_facts['uptime_seconds'] | int / 3600) | round(1) }}"

    - name: Get ipv4 info
      shell: get-ip || ip a | grep 'inet ' | awk '{print $2}'
      register: NETWORK
    - name: Get diskspace info
      shell: df -h | grep -v tmpfs
      register: DF
    - name: Get landscape info
      shell: landscape-sysinfo
      register: LANDSCAPE

    - name: dmesg about r8723bs wlan0 device
      shell: dmesg | grep 8723
      register: DMESG
    - debug:
        var: DMESG.stdout_lines

    - name: Summary
      debug:
        msg:
          - "      hostname: {{ ansible_facts['hostname'] }}"
          - "          ipv4: {{ NETWORK.stdout_lines | join('   ') }}"
          - "            os: {{ ansible_facts['lsb']['description'] }}"
          - "        kernel: {{ ansible_facts['kernel'] }}"
          - "     date time: {{ ansible_facts['date_time']['iso8601'] }}"
          - '   uptime_days: {{ uptime_days }} days'
          - '  uptime_hours: {{ uptime_hours }} hours'
          - '{{ LANDSCAPE.stdout_lines }}'
          - '{{ DF.stdout_lines }}'
      # when: (uptime_days | int) >= 30

    - name: k3s status
      shell: cd /root/k3s-server && bash run-k3s-server.sh ps
      register: APP
    - debug:
        var: APP.stdout_lines

    - name: Extract kubeconfig
      shell: docker cp k3s:/etc/rancher/k3s/k3s.yaml /var/tmp/k3s.yaml
      when: lookup('ansible.builtin.fileglob', './tmp/k3s.yaml') == []
    - name: Fetch kubeconfig
      fetch:
        src: /var/tmp/k3s.yaml
        dest: ./tmp/k3s.yaml
        flat: true
      when: lookup('ansible.builtin.fileglob', './tmp/k3s.yaml') == []
