- hosts: sticks
  become: true
  become_user: root
  tasks:
    - name: Copy cert
      copy:
        src: ./tmp/pgsql-server.pem
        dest: /etc/ssl/pgsql-server.pem
        force: true
        mode: '644'
    - name: Copy app scripts
      copy:
        src: './{{ item.name }}/'
        dest: '/root/{{ item.name }}/'
        force: true
        directory_mode: '700'
        mode: '644'
      loop:
        - { name: k3s-server }
    - name: Run app
      shell: cd /root/{{ item.name }} && bash run-{{ item.name }}.sh up
      loop:
        - { name: k3s-server }
