- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Set fact for uptime_days
      # https://iam-j.github.io/iac/ansible-machine-uptime/
      # https://stackoverflow.com/questions/74318579/how-to-calculate-ansible-uptime-seconds-and-output-this-in-os-csv
      set_fact:
        uptime_days: "{{ (ansible_facts['uptime_seconds'] | int / 86400) | round(1) }}"
    - name: Set fact for uptime_hours
      set_fact:
        uptime_hours: "{{ (ansible_facts['uptime_seconds'] | int / 3600) | round(1) }}"

    - name: Get ipv4 info
      shell: /usr/local/bin/get-ip || ip a | grep 'inet ' | awk '{print $2}'
      register: NETWORK
    - name: Get diskspace info
      shell: df -h | grep -v tmpfs | grep -v devfs
      register: DF
    - name: Get landscape info
      shell: landscape-sysinfo
      register: LANDSCAPE
      when:
        - ansible_facts['distribution'] is defined
        - ansible_facts['distribution'] in ['Ubuntu']

    - name: dmesg about r8723bs wlan0 device
      shell: dmesg | grep 8723
      register: DMESG
      when:
        - ansible_facts['board_name'] is defined
        - ansible_facts['board_name'] in ['STCK1A32WFC']
    - debug:
        var: DMESG.stdout_lines
      when:
        - ansible_facts['board_name'] is defined
        - ansible_facts['board_name'] in ['STCK1A32WFC']

    - name: Summary
      debug:
        msg:
          - "      hostname: {{ ansible_facts['hostname'] }}"
          - "          ipv4: {{ NETWORK.stdout_lines | default(ansible_facts['default_ipv4']['address']) | join('   ') }}"
          # - "       gateway: {{ ansible_facts['default_ipv4']['gateway'] }}"
          - "            os: {{ ansible_facts['lsb']['description'] | default(ansible_facts['distribution'] + ' ' + ansible_facts['distribution_version']) }}"
          - "        kernel: {{ ansible_facts['kernel'] }}"
          - "     date time: {{ ansible_facts['date_time']['iso8601'] }}"
          - '   uptime_days: {{ uptime_days }} days'
          - '  uptime_hours: {{ uptime_hours }} hours'
          - '{{ LANDSCAPE.stdout_lines | default([]) }}'
          - '{{ DF.stdout_lines }}'
      # when: (uptime_days | int) >= 30

    - name: k3s status
      shell: cd {{ ansible_user_dir }}/k3s-server && bash run-k3s-server.sh ps
      register: APP
      when: inventory_hostname in groups['k3sservers']
    - debug:
        var: APP.stdout_lines
      when: inventory_hostname in groups['k3sservers']
