- hosts: microk8sprimary
  become: true
  become_user: root
  tasks:
    - debug:
        msg: "{{ vars['vars']['advertise_ip'] }}"

- hosts: microk8sservers
  become: true
  become_user: root
  tasks:
    - debug:
        msg: "{{ vars['vars']['advertise_ip'] }}"
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
        - inventory_hostname not in groups['microk8sprimary']
