# https://iam-j.github.io/iac/ansible-machine-uptime/
# https://stackoverflow.com/questions/74318579/how-to-calculate-ansible-uptime-seconds-and-output-this-in-os-csv

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Show hostname for sanity check (or just use -v flag for verbose)
      command: hostname
      register: hostname

    # - debug: var=hostname.stdout

    - name: Check uptime seconds
      shell: cut -d ' ' -f1 /proc/uptime
      register: UPTIME_SECONDS

    - name: Set fact for number of days
      set_fact:
        uptime_days: "{{ ( UPTIME_SECONDS.stdout | int / 86400 ) | round(0) }}"

    - name: Set fact for number of hours
      set_fact:
        uptime_hours: "{{ ( UPTIME_SECONDS.stdout | int / 3600 ) | round(0) }}"

    - name: dmesg about r8723bs wlan0 device
      shell: dmesg | grep 8723
      register: DMESG

    - debug: var=DMESG.stdout_lines

    - name: Summary
      debug:
        msg: "Host {{inventory_hostname}} (hostname: {{hostname.stdout}}) has been up for {{uptime_days | int}} days (or {{uptime_hours | int}} hours)"
      # when: (uptime_days | int) >= 30
