- hosts: microk8sservers
  become: true
  become_user: root
  tasks:
    - name: Run commands
      shell: if which microk8s ; then microk8s {{ item.param }} ; fi
      loop:
        - { param: leave }
        - { param: reset }
        - { param: stop }

    - name: Remove microk8s
      community.general.snap:
        name:
          - microk8s
        state: absent
