- hosts: database
  become: true
  become_user: root
  tasks:
    - name: Copy app scripts
      copy:
        src: './{{ item.app }}/'
        dest: '/root/{{ item.app }}/'
        force: true
        directory_mode: '700'
        mode: '644'
      loop:
        - { app: postgres }
    - name: Run app
      shell: cd /root/{{ item.app }} && bash run-{{ item.app }}.sh up
      loop:
        - { app: postgres }
    - name: Fetch cert
      fetch:
        src: /etc/ssl/pgsql-server.pem
        dest: ./tmp/pgsql-server.pem
        flat: true

- hosts: sticks
  become: true
  become_user: root
  tasks:
    - name: Copy cert
      copy:
        src: ./tmp/pgsql-server.pem
        dest: /etc/ssl/pgsql-server.pem
        force: true
        mode: '644'
    - name: Copy app scripts
      copy:
        src: './{{ item.app }}/'
        dest: '/root/{{ item.app }}/'
        force: true
        directory_mode: '700'
        mode: '644'
      loop:
        - { app: k3s-server }
    - name: Template k3s files
      template:
        src: './{{ item.app }}/{{ item.file }}.j2'
        dest: '/root/{{ item.app }}/{{ item.file }}'
        force: true
        mode: '{{ item.mode }}'
      loop:
        - { app: k3s-server, file: docker-compose.yml, mode: '644' }
    - name: Run app
      shell: cd /root/{{ item.app }} && bash run-{{ item.app }}.sh up
      loop:
        - { app: k3s-server }
