- hosts: microk8sservers
  become: true
  become_user: root
  tasks:
    - name: Generate /etc/hosts for microk8s
      lineinfile:
        path: /etc/hosts
        state: present
        create: true
        regexp: '.*{{ item }} #microk8s$'
        line: "{{ hostvars[item]['vars']['advertise_ip'] }} {{ hostvars[item]['ansible_facts']['hostname'] }} #microk8s"
      when: vars['vars']['advertise_ip'] is defined
      loop: "{{ groups['microk8sservers'] | flatten(levels=1) }}"

    - name: Install microk8s
      community.general.snap:
        name:
          - microk8s
        classic: true
        channel: 1.27

    # https://microk8s.io/docs/configure-host-interfaces
    - name: Set advertise-address
      lineinfile:
        path: /var/snap/microk8s/current/args/kube-apiserver
        state: present
        create: true
        regexp: '^--advertise-address='
        line: "--advertise-address={{ vars['vars']['advertise_ip'] }}"
    - name: Set bind-address
      lineinfile:
        path: '{{ item.file }}'
        state: present
        create: true
        regexp: '^--bind-address='
        line: '--bind-address=0.0.0.0'
      loop:
        - { file: /var/snap/microk8s/current/args/kube-apiserver }
        - { file: /var/snap/microk8s/current/args/kube-controller-manager }
        - { file: /var/snap/microk8s/current/args/kube-scheduler }
    - name: Set secure-port
      lineinfile:
        path: '{{ item.file }}'
        state: present
        create: true
        regexp: '^--secure-port='
        line: '--secure-port={{ item.port }}'
      loop:
        - { file: /var/snap/microk8s/current/args/kube-apiserver, port: 16443 }
        - { file: /var/snap/microk8s/current/args/kube-controller-manager, port: 10257 }
        - { file: /var/snap/microk8s/current/args/kube-scheduler, port: 10259 }
    - name: Set node-ip
      lineinfile:
        path: /var/snap/microk8s/current/args/kubelet
        state: present
        create: true
        regexp: '^--node-ip='
        line: "--node-ip={{ vars['vars']['advertise_ip'] }}"
    - name: Set alt_names for cert
      lineinfile:
        path: /var/snap/microk8s/current/certs/csr.conf.template
        state: present
        create: true
        regexp: 'IP.{{ index + 3 }}.* #microk8s$'
        line: "IP.{{ index + 3 }} = {{ hostvars[item]['vars']['advertise_ip'] }} #{{ hostvars[item]['ansible_facts']['hostname'] }} #microk8s"
        insertbefore: '^#MOREIPS'
      when: vars['vars']['advertise_ip'] is defined
      loop: "{{ groups['microk8sservers'] | flatten(levels=1) }}"
      loop_control:
        index_var: index

    - name: Restart microk8s
      shell: snap restart microk8s

    - name: Refresh certs
      shell: microk8s refresh-certs -e server.crt
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
    - name: Wait
      shell: microk8s status --wait-ready

- hosts: microk8sprimary
  become: true
  become_user: root
  tasks:
    - name: Get instructions to add node
      shell: "microk8s add-node | grep {{ vars['vars']['advertise_ip'] }} | head -n1"
      register: JOINCMD
    - debug:
        msg: '{{ JOINCMD.stdout }}'
    - shell: exit 1
      when: (JOINCMD.stdout | length) < 1
    # - debug:
    #     msg: "{{ vars['vars']['advertise_ip'] }}"

- hosts: microk8sservers
  become: true
  become_user: root
  tasks:
    - debug:
        msg: "{% for host in groups['microk8sprimary'] %}{{ hostvars[host]['JOINCMD'].stdout }}{% endfor %} --skip-verify"
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
        - inventory_hostname not in groups['microk8sprimary']
    - name: Run join command
      shell: "{% for host in groups['microk8sprimary'] %}{{ hostvars[host]['JOINCMD'].stdout }}{% endfor %} --skip-verify"
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
        - inventory_hostname not in groups['microk8sprimary']
    # - debug:
    #     msg: "{{ vars['vars']['advertise_ip'] }}"
    #   when:
    #     - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
    #     - inventory_hostname not in groups['microk8sprimary']

- hosts: microk8sprimary
  become: true
  become_user: root
  tasks:
    - name: Extract kubeconfig
      shell: "microk8s config > /var/tmp/kubeconfig.yaml"
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
    - name: Fetch kubeconfig
      fetch:
        src: /var/tmp/kubeconfig.yaml
        dest: ./tmp/kubeconfig.yaml
        flat: true
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []

    - name: Enable microk8s addons
      shell: microk8s enable {{ item.name }}
      loop:
        - { name: dns }
        - { name: community }
        - { name: metrics-server }
        - { name: argocd }
        - { name: cert-manager }
        - { name: traefik } # replaced ingress
        - { name: knative }
        - { name: istio }
        - { name: openebs } # then minio
        - { name: openfaas }
