- hosts: ubuntu
  become: true
  become_user: root
  tasks:
    - name: Set fact for uptime_days
      # https://iam-j.github.io/iac/ansible-machine-uptime/
      # https://stackoverflow.com/questions/74318579/how-to-calculate-ansible-uptime-seconds-and-output-this-in-os-csv
      set_fact:
        uptime_days: "{{ (ansible_facts['uptime_seconds'] | int / 86400) | round(1) }}"
    - name: Set fact for uptime_hours
      set_fact:
        uptime_hours: "{{ (ansible_facts['uptime_seconds'] | int / 3600) | round(1) }}"

    - name: Get diskspace info
      shell: df -h | grep -v tmpfs
      register: DF
    - name: Get landscape info
      shell: landscape-sysinfo
      register: LANDSCAPE

    - name: dmesg about r8723bs wlan0 device
      shell: dmesg | grep 8723
      register: DMESG
    - debug:
        var: DMESG.stdout_lines

    - name: Summary
      debug:
        msg:
          - "      hostname: {{ ansible_facts['hostname'] }}"
          - "          ipv4: {{ ansible_facts['all_ipv4_addresses'] | join(' , ') }}"
          - "            os: {{ ansible_facts['lsb']['description'] }}"
          - "        kernel: {{ ansible_facts['kernel'] }}"
          - "     date time: {{ ansible_facts['date_time']['iso8601'] }}"
          - "   uptime_days: {{ uptime_days }} days"
          - "  uptime_hours: {{ uptime_hours }} hours"
          - "{{ DF.stdout_lines }}"
          - "{{ LANDSCAPE.stdout_lines }}"
      # when: (uptime_days | int) >= 30
