# This file modified from https://medium.com/better-programming/k8s-tips-give-access-to-your-clusterwith-a-client-certificate-dfb3b71a76fe
# and https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jenkinsagent
spec:
  groups:
    - system:authenticated
  request: ${BASE64_CSR}
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
