# This file modified from https://medium.com/better-programming/k8s-tips-give-access-to-your-clusterwith-a-client-certificate-dfb3b71a76fe
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkinsagent-rb
  namespace: jenkinsagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkinsagent-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group # Match Organization (O) in CSR
    name: jenkinsagent-o
