# This file modified from https://medium.com/better-programming/k8s-tips-give-access-to-your-clusterwith-a-client-certificate-dfb3b71a76fe
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkinsagent-role
  namespace: jenkinsagent
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - create
      - get
      - update
      - list
      - delete
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - update
      - list
      - delete
