## See more docs at https://hub.docker.com/r/atlassian/bitbucket-server/
version: "3.5"

services:
    bitbucket:
        container_name: bitbucket-7.11.2
        image: atlassian/bitbucket-server:7.11.2
        ports:
            - 127.0.0.1:7990:7990
            - 127.0.0.1:7999:7999
        restart: unless-stopped
        volumes:
            - data:/var/atlassian/application-data/bitbucket

volumes:
    data:
